//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pindlebot.rc
//
#define IDC_RUN                         3
#define IDC_CLEANALL                    3
#define IDC_ITEMLOG                     3
#define IDC_REMOVEACTION                3
#define IDC_SETTING                     4
#define IDC_EDITACTION                  4
#define IDC_HISTORYLOG                  4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define TMR_MAINFLOW                    101
#define IDD_PINDLEBOT_DIALOG            102
#define ID_TMR_MAIN                     102
#define ID_TMR_CHECKSTATS               106
#define ID_TMR_AUTOSTOP                 107
#define CG_IDD_PROGRESS                 108
#define ID_TMR_CHECKERROR               114
#define ID_TMR_AUTOSTART                116
#define IDR_MAINFRAME                   128
#define IDD_GENERAL                     129
#define IDD_CREATEGAME                  130
#define IDD_SKILLS                      131
#define IDD_DELAY                       132
#define IDI_ICON1                       133
#define IDR_MENU2                       135
#define IDI_SORC                        137
#define IDI_PORTAL                      139
#define IDD_COORDSDLG                   140
#define IDD_LOGINDLG                    142
#define IDI_DARK                        143
#define IDI_LIGHT                       144
#define IDD_INPUTDLG                    145
#define IDI_LOGIN                       146
#define IDI_OPEN                        147
#define IDI_SEXCLAMATION                149
#define IDI_SINFORMATION                150
#define IDD_SAFETY                      151
#define IDI_ICON2                       154
#define IDD_PICKITDLG                   155
#define IDD_STATISTICSDLG               156
#define IDD_ITEMLOGDLG                  158
#define IDD_CHARSPEC                    161
#define IDD_CHARSETDLG                  162
#define IDD_CHARCLASSDLG                163
#define IDD_NEWCHARDLG                  165
#define IDI_QUESTIONMARK                167
#define IDD_ACTIONLISTDLG               168
#define IDD_ACTIONDLG                   169
#define IDD_INIFILEDLG                  171
#define IDD_MONSTERATTRDLG              172
#define IDD_ANALYSISDLG                 174
#define IDD_HISTORYDLG                  175
#define IDI_SMALLSORC_ACTIVE            176
#define IDI_SMALLSORC_INACTIVE          177
#define IDI_SORC_ACTIVE                 178
#define IDI_SORC_INACTIVE               179
#define IDR_POPUP_MENU                  180
#define IDD_SAFETYDLG                   181
#define IDD_SAFETYSCHEMENAME            182
#define IDR_ITEMLOG                     183
#define IDD_SAFETYPAGE                  185
#define IDC_D2TITLE                     1000
#define IDC_JOIN                        1001
#define IDC_EXIT                        1002
#define IDC_NAMEPREFIX                  1002
#define IDC_USEPREFIX                   1002
#define IDC_NAMESURFIX                  1003
#define IDC_COLDARMOR                   1003
#define IDC_LAUNCH                      1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_STATISTICS                  1003
#define IDC_PWDPREFIX                   1004
#define IDC_ENERGYSHIELD                1004
#define IDC_LOGIN                       1004
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_PWDSURFIX                   1005
#define IDC_THUNDERSTORM                1005
#define IDC_CONNECTTOCHANNEL            1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_COLDARMORKEY                1006
#define IDC_WALK                        1006
#define IDC_ENERGYSHIELDKEY             1007
#define IDC_ERRORDELAY                  1007
#define IDC_THUNDERSTORMKEY             1008
#define IDC_TELEPORTKEY                 1009
#define IDC_STATICFIELD                 1010
#define IDC_ORBKEY                      1011
#define IDC_STATICFIELDKEY              1012
#define IDC_ORBREP                      1013
#define IDC_STATICFIELDREP              1014
#define IDC_SFLABEL                     1015
#define IDC_DEFAULTVAL                  1018
#define IDC_RAND                        1019
#define IDC_LOCATIONRAND                1019
#define IDC_SPIN1                       1020
#define IDC_RESTOREDEF                  1020
#define IDC_DEFAULTRAND                 1021
#define IDC_PINDLEID                    1021
#define IDC_SPIN2                       1021
#define IDC_MALAHID                     1022
#define IDC_TIMERAND                    1022
#define IDC_SPIN3                       1022
#define IDC_QUALID                      1023
#define IDC_TIMESPIN                    1023
#define IDC_LARZUKID                    1024
#define IDC_ABIN                        1025
#define IDC_PORTALID                    1025
#define IDC_D2EXE                       1028
#define IDC_BUTTON1                     1029
#define IDC_NEW                         1029
#define IDC_CHAR1                       1030
#define IDC_DELCHAR                     1030
#define IDC_MOVEUP                      1030
#define IDC_SAFETY_REMOVE               1030
#define IDC_EDIT                        1030
#define IDC_EDITCHAR                    1031
#define IDC_DELETE                      1031
#define IDC_CHECK1                      1032
#define IDC_EDIT1                       1033
#define IDC_CHECK2                      1033
#define IDC_CLEAR                       1033
#define IDC_SILENTMODE                  1033
#define IDC_PWD2                        1034
#define IDC_RESMERC                     1034
#define IDC_CHECK3                      1034
#define IDC_TELEPORTDELAY               1034
#define IDC_MAXHP                       1034
#define IDC_AUTOREPLY                   1034
#define IDC_REPEAT                      1034
#define IDC_REPAIR                      1035
#define IDC_CHECK4                      1035
#define IDC_PRIMARYDELAY                1035
#define IDC_MAXMP                       1035
#define IDC_PWD1                        1036
#define IDC_REPAIRAFTER                 1036
#define IDC_CHECK5                      1036
#define IDC_PWDLEN1                     1036
#define IDC_ACCT                        1037
#define IDC_RETREAT                     1037
#define IDC_AUTORESTART                 1037
#define IDC_PWDLEN2                     1037
#define IDC_RETREATHP                   1038
#define IDC_REPRESTART                  1038
#define IDC_CHANNELNAME                 1038
#define IDC_CHAR2                       1039
#define IDC_COMBO11                     1039
#define IDC_BMALAHMP                    1039
#define IDC_PREFIX                      1039
#define IDC_CHAR3                       1040
#define IDC_COMBO12                     1040
#define IDC_FullSCREEN                  1040
#define IDC_MALAHMP                     1040
#define IDC_CHAR4                       1041
#define IDC_HARDCOREDEF                 1041
#define IDC_WINDOWMODE                  1041
#define IDC_CHAR5                       1042
#define IDC_PARAM_NS                    1042
#define IDC_ALERTHP                     1042
#define IDC_CHAR6                       1043
#define IDC_TITLE                       1043
#define IDC_PARAM_SKIPTOBNET            1043
#define IDC_BWATCHMP                    1043
#define IDC_CHAR7                       1044
#define IDC_CURETEAM                    1044
#define IDC_DATE                        1044
#define IDC_PARAM_LQ                    1044
#define IDC_ALERTMP                     1044
#define IDC_CHAR8                       1045
#define IDC_HOMEPAGE                    1045
#define IDC_TITLE2                      1045
#define IDC_PARAM_W                     1045
#define IDC_BWATCHMERC                  1045
#define IDC_PICKGOLD                    1046
#define IDC_VERSION                     1046
#define IDC_POTIONHP                    1046
#define IDC_COMBO21                     1047
#define IDC_POTIONMP                    1047
#define IDC_COMBO22                     1048
#define IDC_DUMMY1                      1048
#define IDC_MOVEAMULET                  1048
#define IDC_POTIONMERC                  1048
#define IDC_COMBO31                     1049
#define IDC_STATICDELAY                 1049
#define IDC_MOVEJEWEL                   1049
#define IDC_COMBO32                     1050
#define IDC_MOVESMALLCHARM              1050
#define IDC_COMBO41                     1051
#define IDC_CURSTATE                    1051
#define IDC_MOVERUNE                    1051
#define IDC_COMBO42                     1052
#define IDC_COLDARMORS                  1052
#define IDC_MOVEGOLD                    1052
#define IDC_COMBO51                     1053
#define IDC_PRIMARYS                    1053
#define IDC_CLOSETIME                   1053
#define IDC_MOVEFLAWLESSGEM             1053
#define IDC_COMBO52                     1054
#define IDC_CLOSEDATE                   1054
#define IDC_DEPOSITPER                  1054
#define IDC_AUTOCLOSE                   1055
#define IDC_LIST1                       1056
#define IDC_TOTALGAMES                  1057
#define IDC_PINDLEKILLED                1058
#define IDC_RETREATED                   1059
#define IDC_CHARDIED                    1060
#define IDC_MERCDIED                    1061
#define IDC_CRASHED                     1062
#define IDC_POTIONDRUNK                 1062
#define IDC_STARTTIME                   1063
#define IDC_CURRENTTIME                 1064
#define IDC_TOTALTIME                   1065
#define IDC_END_NOW_TIME                1066
#define IDC_LOCATIONSPIN                1067
#define IDC_DEADLYCOMBO                 1067
#define IDC_HISTORYSINCE                1068
#define IDC_HISTORYGAMENUM              1069
#define IDC_NETEFFECTIVE                1069
#define IDC_HISTORYKILL                 1070
#define IDC_GROSSEFFECT                 1070
#define IDC_RADIO1                      1071
#define IDC_INSUFFICIENTSKILL           1071
#define IDC_RADIO2                      1072
#define IDC_RADIO3                      1073
#define IDC_SAVEPASSWORD                1074
#define IDC_REPLACE                     1075
#define IDC_MODIFYINI                   1076
#define IDC_REFRESH                     1077
#define IDC_CLIENTWALK                  1077
#define IDC_CHARLIST                    1078
#define IDC_VERIFYSTEP                  1078
#define IDC_TOWNVERIFY                  1078
#define IDC_BMALAHHP                    1079
#define IDC_MALAHHP                     1080
#define IDC_BWATCHHP                    1081
#define IDC_ADDCHAR                     1082
#define IDC_WATCHPOTIONHP               1082
#define IDC_CHARNAME                    1083
#define IDC_WATCHPOTIONMP               1083
#define IDC_SPIN_MALAHHP                1084
#define IDC_SPIN_MALAHMP                1085
#define IDC_SPIN_ALERTHP                1086
#define IDC_IGNOREMERC                  1086
#define IDC_SPIN_ALERTMP                1087
#define IDC_SHOWSETTINGS                1088
#define IDC_SPIN_POTIONHP               1088
#define IDC_GAMENAMELENGTH              1089
#define IDC_SPIN_POTIONMP               1089
#define IDC_CREATECHANNEL               1090
#define IDC_WATCHPOTIONMERC             1090
#define IDC_USEAUTOREPLY                1091
#define IDC_SPIN_POTIONMERC             1091
#define IDC_NEWCHAR                     1092
#define IDC_BEFORERED                   1093
#define IDC_USEFINDITEM                 1094
#define IDC_AFTERRED                    1095
#define IDC_COMBO1                      1095
#define IDC_ONPINDLESKIN                1096
#define IDC_ADDACTION                   1096
#define IDC_COMBO2                      1096
#define IDC_ONCORPOSE                   1097
#define IDC_TARGETLIST                  1097
#define IDC_SKILLLIST                   1098
#define IDC_LEFT                        1099
#define IDC_RIGHT                       1100
#define IDC_CASTDELAY                   1101
#define IDC_MOVEDOWN                    1102
#define IDC_SHOWOVERHEADMSG             1103
#define IDC_NORMAL                      1104
#define IDC_NIGHTMARE                   1105
#define IDC_HELL                        1106
#define IDC_COOLDOWN                    1107
#define IDC_MOVERING                    1109
#define IDC_SELECTFILE                  1110
#define IDC_FILE                        1115
#define IDC_OTHERPARAMS                 1116
#define IDC_ATTRLIST                    1117
#define IDC_ADDCOMBO                    1118
#define IDC_REMOVECOMBO                 1119
#define IDC_DESC                        1119
#define IDC_ANA_DEADLYCOMBO             1120
#define IDC_IMMUNITY                    1120
#define IDC_ANA_RETREAT                 1121
#define IDC_AUTOTITLE                   1121
#define IDC_ANA_CHARDEAD                1122
#define IDC_CUSTOMTITLE                 1122
#define IDC_ANA_MERCDEAD                1123
#define IDC_CLEARHISTORY                1124
#define IDC_ANA_INSUFFICIENTSKILL       1125
#define IDC_VIEWSAFETYSCHEMES           1128
#define IDC_REMOVESAFETYSCHEMES         1129
#define IDC_COPYTOCLIPBOARD             1130
#define IDC_ADDSAFETYSCHEMES            1130
#define IDC_SAFETYLIST                  1131
#define IDC_SELECTSAFETYSCHEMES         1132
#define IDC_AMMO                        1132
#define IDC_AMMOBUYQTY                  1133
#define IDC_SKILLSCHEME                 1134
#define IDC_SAFETYSCHEMES               1135
#define IDC_ABOUT                       32771
#define ID_APP_HELP                     32772
#define ID_HELP_CHECKUPGRADE            32773
#define ID_POPUP_RESTORE                32774
#define ID_POPUP_STATISTICS             32775
#define ID_POPUP_ABOUT                  32779
#define ID_POPUP_ITEMLOG                32780
#define ID_POPUP_ACTIVATED2WND          32781
#define ID_POPUP_SETTINGS               32782
#define ID_POPUP_HELP                   32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
